version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"

  - package-ecosystem: "gomod"
    directory: "/pgk/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"
